### ISSUE TITLE
Fails to build with GHC 9.6.2 and the latest hackage index

### ISSUE THREAD

**Issue by epoberezkin** [haskell/entropy#83]
The package builds if `unix` package is fixed to 2.8.1.1, but fails with the latest 2.8.2.0.

The error:

```
Configuring entropy-0.4.1.10...
/var/folders/cb/q9yg95_s3fq47zqp76x254940000gn/T/75294-0.c: checkForInteriorNuls: invalid argument (POSIX filepaths must not contain internal NUL octets.)
Error: cabal: Failed to build entropy-0.4.1.10
```

**Comment by andreasabel** [comment]
Building with GHC 9.6.5 succeeds: https://github.com/haskell/entropy/actions/runs/9161244968/job/25185650529

Closing, please reopen if necessary.
