### ISSUE TITLE
Can we do a release for cabal 3.12?

### ISSUE THREAD

**Issue by soulomoon** [haskell/entropy#84]
As the title

**Comment by soulomoon** [comment]
Blocking 
https://github.com/haskell/haskell-language-server/issues/4196

**Comment by soulomoon** [comment]
Need to update to use `SymbolicPath `

**Comment by ysangkok** [comment]
@TomMD, since I have seen you merged #79, would you be interested in doing this bump too?

**Comment by andreasabel** [comment]
Fixed by revision 2: https://hackage.haskell.org/package/entropy-0.4.1.10/revisions/
